---
title: "fundamentals of ggplot"
author: "Ward, A; Parsons, R."
format: 
  pdf: default
editor: visual
---

```{r}
# install.packages("ggplot2")
library(ggplot2)
library(here)

# Read in the data and store as "ci_np" data object
ci_np <- read.csv("ci_np.csv")

# display the first 6 rows
head(ci_np)

#look at column names
colnames(ci_np)
```

#### Graphing Time YAY

```{r}
ggplot(data = ci_np)

#try again w/ mapping
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) 

#Scatterplot
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) +
  geom_point()

#Column graph
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) +
  geom_col()

#Line plot
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) +
  geom_point() +
  geom_line()

#Smooth line
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) +
  geom_point() +
  geom_smooth()

#Linear model
#Smooth line
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) +
  geom_point() +
  geom_smooth(method = "lm")
```

#### Single variables

```{r}
#Histogram
ggplot(data = ci_np, mapping = aes(x = visitors)) +
  geom_histogram()

#Density Plot
ggplot(data = ci_np, mapping = aes(x = visitors)) +
  geom_density()
```

#### Modifying plot points

```{r}
#Color and shape
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) +
  geom_point(shape = 8, color = "blue")

#Again!
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) +
  geom_point(shape = 3, color = "red")

#Modifying line plot
ggplot(data = ci_np, mapping = aes(x = year, y = visitors)) +
  geom_point(color = "green") + #changed the dot color to be prettier
  geom_line(linetype = "dashed", color = "green")

```

#### Mapping other variables onto aesthetics

```{r}
#Size of points vary w/ vistors
ggplot(ci_np, aes(x = year, y = visitors)) +
  geom_point(aes(size = visitors))

#Changing color
ggplot(ci_np, aes(x = year, y = visitors)) +
  geom_point(aes(size = visitors,
                 color = visitors))
```

#### All CA!

```{r}
#Read in data
ca_np <- read.csv("ca_np.csv")


# Fetch the column but with the output run through the unique() function
unique(ca_np$park_name)
```

#### Plots of visitors

```{r}
#visitors per park per year
ggplot(data = ca_np, mapping = aes(x = year, y = visitors)) +
  geom_point()

#color vary w/ park
ggplot(data = ca_np, mapping = aes(x = year, y = visitors, color = park_name)) +
  geom_point() +
  geom_line()

#Faceting parks
ggplot(data = ca_np, mapping = aes(x = year, y = visitors)) +
  geom_point(aes(color = park_name)) +
  facet_wrap(park_name ~ .)

#Free the scales 
ggplot(data = ca_np, mapping = aes(x = year, y = visitors)) +
  geom_point(aes(color = park_name)) +
  facet_wrap(park_name ~ ., scales = "free_y")
```

#### Abalone Landings

```{r}
# Read in the data
ab_land <- read.csv("abalone_landings.csv")

# display the first 6 rows
head(ab_land)

#look at column names
colnames(ab_land)
```

#### Data exploration notes:

-   "While" should be "white"

-   Landings by year per species easy comparison

-   Changes in landings over time

Our research question:

How have landings for different species of abalone changed over time?

```{r}
ggplot(ab_land, aes(x = Year, y = Abalone_Landings_lbs, color = Abalone_Species))+
  geom_point()+
  geom_line()
```
